services:
  django:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/staticfiles:/staticfiles
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static:ro
    ports:
      - "80:80"
    depends_on:
      - django
